version: "3.8"

services:
  strimdl:
    build: .
    container_name: strimdl
    restart: unless-stopped
    ports:
      - "${PORT:-10001}:10001"
    environment:
      - TZ=${TZ}
      - LANG=${LANG}
      - VIDEO_NAMING_PATTERN=${VIDEO_NAMING_PATTERN}
      - IMAGE_NAMING_PATTERN=${IMAGE_NAMING_PATTERN}
      - STRIMDL_USER=${STRIMDL_USER}
      - STRIMDL_PASS=${STRIMDL_PASS}
    volumes:
      - "${DOWNLOAD_PATH}:/download"
    command: /app/server.py

